### ISSUE TITLE
When gorm tries to insert in batches, clickhouse-go fails

### ISSUE THREAD

**Issue by rusenask** [go-gorm/clickhouse#11]
## Description

Seems like when gorm tries to insert in batches, clickhouse-go return an error:

```
data request has already been prepared in transaction
```

https://github.com/ClickHouse/clickhouse-go/blob/master/clickhouse.go#L69-L70

Workaround is just not to use batches, clickhouse can accept really large payloads. Posting just in case anyone encounters this

**Comment by jinzhu** [comment]
Hi @rusenask 

You can just use `Create` to insert data in batches like described in the README.
