### ISSUE TITLE
Nullable ClickHouse columns

### ISSUE THREAD

**Issue by pycckuu** [go-gorm/clickhouse#13]
## Your Question

I was wondering if it is possible to use GORM Auto-migration tools and setup Nullable columns in tables. All approaches I tried did not allow me to do that (either breaks with SIGs, or saying that null is not allowed). The only way I found (tried many approaches including null package, sql.NullStrings etc) is to create tables via raw sql. For example, 

```go
	err = db.Exec(`
	CREATE TABLE IF NOT EXISTS orders (
			id UInt32,
			completed_at DateTime,
			datawarehoused_at Nullable(DateTime),
			user_id Nullable(UInt32),	
		) engine=MergeTree PARTITION BY toYYYYMM(completed_at) ORDER BY completed_at SETTINGS index_granularity = 8192
	`).Error
```
And then in the GORM model I can use pointer in the struct fields 

```go

type Order struct {
	ID                     int32      `json:"id" gorm:"primaryKey"`
	CompletedAt            time.Time  `json:"completed_at"`
	DatawarehousedAt       time.Time  `json:"datawarehoused_at"`
	UserId                 *int32     `json:"user_id" `
}
```

The only problem with this approach that I am missing AutoMigration tools, thus I need to write all migrations manually.

## Expected answer

Is there a better way? Am I missing something? 
I want:
1. Nullable columns
2. AutoMigrations

**Comment by msidorenko** [comment]
@pycckuu  
A best way to do it, modify `migrator.go` and add check for `field.DefaultValue` at line 48 
Something like that: 
replace
`expr.SQL += " DEFAULT " + field.DefaultValue`

with
```golang
switch field.DefaultValue {
    case "(-)":
        expr.SQL += " DEFAULT " + field.DefaultValue
        break
    case "null":
        expr.SQL = fmt.Sprintf("Nullable(%s)", expr.SQL)
	break
}
```

So, you're structure can be something like that:
```golang
type Order struct {
	ID                     int32      `gorm:"primaryKey"`
	CompletedAt            time.Time 
	DatawarehousedAt       time.Time  `gorm:"default:null"`
	UserId                 *int32     
}
```

I can create a pull request if @jinzhu will agree

**Comment by jinzhu** [comment]
Define the model like this?

```go
type User struct {
	ID        uint
	CreatedAt time.Time
	UpdatedAt time.Time `gorm:"type:Nullable(DateTime)"`
}
```

**Comment by muety** [comment]
Got a similar problem here.

```go
type CustomTime time.Time

func (t CustomTime) Value() (driver.Value, error) {
    return time.Time(t).Round(time.Millisecond), nil
}

func (t *CustomTime) Scan(value interface{}) error {
    // ...
}  

type User struct {
    // ...
    Foobar *CustomTime
}
```

When trying to insert an instance of `User`, I'm getting a panic like this:

```
 panic: value method myproject.CustomTime.Value called using nil *CustomTime pointer
 
 -> myproject.(*CustomTime).Value
    <autogenerated>:1 +0x6d
    github.com/ClickHouse/clickhouse-go/v2/lib/column.(*DateTime).AppendRow
      /home/ferdinand/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.30.0/lib/column/datetime.go:263
    github.com/ClickHouse/clickhouse-go/v2/lib/proto.(*Block).Append
      /home/ferdinand/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.30.0/lib/proto/block.go:62
    github.com/ClickHouse/clickhouse-go/v2.(*batch).Append
      /home/ferdinand/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.30.0/conn_batch.go:132
    github.com/ClickHouse/clickhouse-go/v2.(*stdBatch).Exec
      /home/ferdinand/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.30.0/clickhouse_std.go:396
    github.com/ClickHouse/clickhouse-go/v2.(*stdBatch).ExecContext
      /home/ferdinand/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.30.0/clickhouse_std.go:408
 (...)
```

When explicitly declaring the `gorm:"type:Nullable(DateTime)"`, the column will still end up as type `DateTime` and the error persists. 

It would be cool if (a) the driver wouldn't crash in case a `nil` pointer is passed for a nullable field and (b) if the driver itself would properly choose a nullable type for the column.
