### ISSUE TITLE
not support cluster now ?   ON CLUSTER cluster_name

### ISSUE THREAD

**Issue by 1stmud** [go-gorm/clickhouse#16]
## Your Question
When I looked at the code again, I didn't find a way to support cluster. How can CreateTable support ON CLUSTER syntax?

CREATE TABLE [IF NOT EXISTS] [db.]table_name [ON CLUSTER cluster]
(
    name1 [type1] [DEFAULT|MATERIALIZED|ALIAS expr1],
    name2 [type2] [DEFAULT|MATERIALIZED|ALIAS expr2],
    ...
) ENGINE = engine

**Comment by pozen** [comment]
Yes, this is very important

**Comment by pozen** [comment]
https://github.com/go-gorm/clickhouse/pulls ,  @jinzhu check this please
