### ISSUE TITLE
官方的可以，这个根本不行啊

### ISSUE THREAD

**Issue by zhaojia123** [go-gorm/clickhouse#171]
OpenDB方法不存在，用dsn链接 就说用户名密码错误。工具都可以链接，官方的也可以，就这个不行

**Comment by jinzhu** [comment]
README 写的有点错误，修正了下

**Comment by zhaojia123** [comment]
> README 写的有点错误，修正了下

dsn := "clickhouse://gorm:gorm@localhost:9942/gorm?dial_timeout=10s&read_timeout=20s" 
dsn := "clickhouse://username:password@host:port/database?dial_timeout=10s&read_timeout=20s"??? why? failed to initialize database, got error parse
