### ISSUE TITLE
把clickhouse driver 的引用去掉

### ISSUE THREAD

**Issue by zhusichuang** [go-gorm/clickhouse#18]
## Describe the feature

把clickhouse driver 的引用去掉
## Motivation

将clickhouse driver 的引用去掉，由用户自己去选择使用哪个driver。
目前我想使用http的click house driver，发现这个包并不支持，因此想让这个包去掉clickhouse driver的引用。

**Comment by jinzhu** [comment]
the latest clickhouse driver should support the http interface.
