### ISSUE TITLE
Set new tag

### ISSUE THREAD

**Issue by icecube092** [go-gorm/clickhouse#20]

**Comment by jinzhu** [comment]
use `v0.2.0`

**Comment by icecube092** [comment]
v0.2.0 doesn't exists

**Comment by icecube092** [comment]
> ## Please set new tag, I need Delete support
> ## The document you expected this should be explained
> ## Expected answer



> use `v0.2.0`
v0.2.0 doesn't exists

**Comment by icecube092** [comment]
v0.2.0 doesn't exists

**Comment by jinzhu** [comment]
Should be added.
