### ISSUE TITLE
Run Create in two goroutines

### ISSUE THREAD

**Issue by norguhtar** [go-gorm/clickhouse#33]
## Description

When i try use Create for batch as discribed in README it work fine. But when i run Create in two goroutines simultaneously this run transaction in second goroutne, and this broken. In logs i'm get
```
[clickhouse][connect=3][begin] tx=false, data=false
[clickhouse][connect=3][commit] tx=true, data=false
```

And got error 
```
data request has already been prepared in transaction
``` 

If i'm disable transaction support via gorm. Just add 
```
SkipDefaultTransaction: true
```

I can't use batch mode
```
insert statement supported only in the batch mode (use begin/commit)
```

But clickhouse not suport transaction. But if i try use batch fro clickhouse i should enable transaction. It's really strange thing.

**Comment by jinzhu** [comment]
Can you create a reproducible PR?
