### ISSUE TITLE
2022/03/25 09:12:20 /mnt/d/code/sidsa-service/pkg/database/clickhouse.go:24 [error] failed to initialize database, got error driver: bad connection clickhouse conn fail:driver: bad connection Error: clickhouse conn fail:driver: bad connection

### ISSUE THREAD

**Issue by shuwenhe** [go-gorm/clickhouse#39]
2022/03/25 09:12:20 /mnt/d/code/sidsa-service/pkg/database/clickhouse.go:24
[error] failed to initialize database, got error driver: bad connection
clickhouse conn fail:driver: bad connection
Error: clickhouse conn fail:driver: bad connection

**Comment by jinzhu** [comment]
just upgraded the driver, please check if still have any issue.
