### ISSUE TITLE
Error initializing connection

### ISSUE THREAD

**Issue by yimengyisheng** [go-gorm/clickhouse#41]
ClickHouse Version:  21.3.14.1.7

Conn Code:
url := fmt.Sprintf("http://%v:%v?database=%v&username=%v&password=%v&read_timeout=10&write_timeout=20",
		cfg.Host, cfg.Port, cfg.Dbname, cfg.User, cfg.Password)
	clickHouseDb, err := gorm.Open(clickhouse.Open(url), &gorm.Config{})

Err Info:
panic: runtime error: invalid memory address or nil pointer dereference

**Comment by jinzhu** [comment]
refer https://github.com/ClickHouse/clickhouse-go for the dsn format.
