### ISSUE TITLE
是否可以升级到 clickhouse-go/v2

### ISSUE THREAD

**Issue by qingbozhang** [go-gorm/clickhouse#48]
## Describe the feature
是否可以升级到 clickhouse-go/v2 官方说性能会更好

## Motivation
[significantly faster than v1](https://github.com/ClickHouse/clickhouse-go#benchmark).

**Comment by gfunc** [comment]
and I had a problem with Decimal type where `Decimal(19,2)` would be scanned into gibberish (golang type []unint8), and Decimal(10.2) would be scanned into Int64 which would be 100x the original value. 

Manually upgraded to v2 by basically changing nothing but import, and dsn string should be changed to `clickhouse://user:passwd@127.0.0.1:9000/db?param1=value1` .
no problem found ATM

**Comment by qingbozhang** [comment]
+1

**Comment by gfunc** [comment]
found a problem with query variables, would need to change the `BindVarTo` function based on this [link](https://github.com/ClickHouse/clickhouse-go/blob/a0caf672cd2886fa679ec716e35677ad2224bfe4/examples/std/bind/main.go#L73)

quick fix here
```go
func (dialector Dialector) BindVarTo(writer clause.Writer, stmt *gorm.Statement, v interface{}) {
	for _, b := range []byte(fmt.Sprintf("$%d", len(stmt.Vars))) {
		writer.WriteByte(b)
	}
}
```

**Comment by askuy** [comment]
+1

**Comment by exqlnet** [comment]
+1

**Comment by jinzhu** [comment]
v0.4.0 upgrade to `clickhouse-go/v2`

**Comment by jinzhu** [comment]
need to change the `dsn` format before upgrade
