### ISSUE TITLE
support clickhouse array type

### ISSUE THREAD

**Issue by wilson-wc** [go-gorm/clickhouse#53]
##

**Comment by LavanyaRavi22** [comment]
@wilson-wc Would you mind telling me how you fixed this? I wasn't able to find any array type.

**Comment by wilson-wc** [comment]
hello，if u wanna use an array contains int ，u might use []*int64 ,it works for me.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Lavanya Ravinthiran ***@***.***>
发送时间: Monday, July 11, 2022 8:52:14 AM
收件人: go-gorm/clickhouse ***@***.***>
抄送: wilson-wc ***@***.***>; Mention ***@***.***>
主题: Re: [go-gorm/clickhouse] support clickhouse array type (Issue #53)


@wilson-wc<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwilson-wc&data=05%7C01%7C%7Cfe833897d3db47fb10d108da62d798fd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637930975386926811%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hr7Oxd64xiRTnKZsSZ5KhHv1Vvsr3ixlt4brp5MEBdA%3D&reserved=0> Would you mind telling me how you fixed this? I wasn't able to find any array type.

―

**Comment by hzh12131108** [comment]
May I ask how you solved this problem

**Comment by yangyang5214** [comment]
try this,

```
package types

import (
	"database/sql/driver"
	"strings"
)

type StringArray []string

func (a *StringArray) Scan(value interface{}) error {
	*a, _ = value.([]string)
	return nil
}

func (a StringArray) Value() (driver.Value, error) {
	if len(a) == 0 {
		return "[]", nil
	}
	for i := range a {
		a[i] = "'" + a[i] + "'"
	}
	return "[" + strings.Join(a, ",") + "]", nil
}
```
